version: '3'
services:
  movies-api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    ports:
      - '9000:9000'
    environment:
      - MONGODB_URI=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017
      - REDIS_URI=redis://redis
      - ENABLE_WRITING_HANDLERS=false 
    networks:
      - movies-network
      - redis-network
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:8.0-rc
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    networks:
      - movies-network
    volumes:
      - mongodb-data:/data/db

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - redis-network

networks:
  movies-network:
    driver: bridge
  redis-network:
    driver: bridge

volumes:
  mongodb-data:
